name: eshop
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.1
  get: ^4.6.1
  dio: ^4.0.4
  image_picker: ^0.8.4+4

  number_picker:
    path: number_picker

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/icons/
    - lib/assets/icons/shops.png
    - lib/assets/icons/download.jpg
    - lib/assets/icons/profile.png
    - lib/assets/icons/icfav.png
    - lib/assets/icons/product.png
